void tt(){
if(String(c[r])=="0"){
  myText=String(gh[0],BIN);
    }
if(String(c[r])=="1"){
  myText=String(gh[1],BIN);
}
if(String(c[r])=="2"){
  myText=String(gh[2],BIN);
}
if(String(c[r])=="3"){
  myText=String(gh[3],BIN);
}
if(String(c[r])=="4"){
  myText=String(gh[4],BIN);
}
if(String(c[r])=="5"){
  myText=String(gh[5],BIN);
}
if(String(c[r])=="6"){
  myText=String(gh[6],BIN);
}
if(String(c[r])=="7"){
  myText=String(gh[07],BIN);
}
if(String(c[r])=="8"){
  myText=String(gh[8],BIN);
}
if(String(c[r])=="9"){
  myText=String(gh[9],BIN);
}
if(String(c[r])=="a"){
  myText=String(gh[10],BIN);
}
if(String(c[r])=="b"){
  myText=String(gh[11],BIN);
}
if(String(c[r])=="c"){
  myText=String(gh[12],BIN);
}
if(String(c[r])=="d"){
  myText=String(gh[13],BIN);
}
if(String(c[r])=="e"){
  myText=String(gh[14],BIN);
}
 if(String(c[r])=="f"){
  myText=String(gh[15],BIN);
  }
 }
